name: cd

on:
  workflow_dispatch:
  push:
    tags: [ v-* ]

env:
  node-version: 20.x

jobs:
  cd:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-yarn-${{ env.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive --production
      - name: Checkout prod env
        run: yarn env:checkout prod
      - name: Pull remote state
        run: yarn pull
      - name: Deploy
        run: yarn deploy
